# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
