# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160318_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_price',
            field=models.IntegerField(),
        ),
    ]
